#include "TestTrdTickAna.h"

TestTrdTickAna::TestTrdTickAna()
{
}

TestTrdTickAna::~TestTrdTickAna()
{
}

void TestTrdTickAna::RunTest()
{
  TrdTickAna tta(2);
  CPPUNIT_ASSERT(tta.IMBNmlzd() == 0);
  CPPUNIT_ASSERT(tta.IMBRaw() == 0);

  TradeTick trade_tick;

  trade_tick.hms = HMS( 9, 15, 1 ); trade_tick.Price = 21050; trade_tick.Volume = 23; trade_tick.Initiator =  -1; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -   1) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  -23 ) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - -1            ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  23           ) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0           ) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 15, 11); trade_tick.Price = 21050; trade_tick.Volume = 89; trade_tick.Initiator =  1 ; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -   2) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  66  ) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - 1.1785714286  ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  56           ) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.5         ) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 15, 21); trade_tick.Price = 21050; trade_tick.Volume = 26; trade_tick.Initiator =  -1; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -   3) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  40  ) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - 0.8695652174  ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  46           ) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.3333333333) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 15, 31); trade_tick.Price = 21050; trade_tick.Volume = 38; trade_tick.Initiator =  1 ; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -   4) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  78  ) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - 1.7727272727  ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  44           ) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.5         ) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 15, 41); trade_tick.Price = 21050; trade_tick.Volume = 89; trade_tick.Initiator =  -1; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -   5) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  -11 ) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - -0.2075471698 ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  53           ) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.4         ) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 15, 51); trade_tick.Price = 21050; trade_tick.Volume = 72; trade_tick.Initiator =  -1; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -   6) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  -83 ) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - -1.4777448071 ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  56.1666666667) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.3333333333) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 16, 1 ); trade_tick.Price = 21050; trade_tick.Volume = 75; trade_tick.Initiator =  -1; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -   7) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  -158) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - -2.6844660194 ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  58.8571428571) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.2857142857) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 16, 11); trade_tick.Price = 21050; trade_tick.Volume = 27; trade_tick.Initiator =  -1; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -   8) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  -185) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - -3.3712984055 ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  54.875       ) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.25        ) < 0.01); CPPUNIT_ASSERT(abs(tta.CovInitr() -  -0.3214285714) < 0.01); CPPUNIT_ASSERT(abs(tta.CorrInitr() - -0.4285714286) < 0.01);
  trade_tick.hms = HMS( 9, 16, 21); trade_tick.Price = 21050; trade_tick.Volume = 98; trade_tick.Initiator =  1 ; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -   9) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  -87 ) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - -1.4581005587 ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  59.6666666667) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.3333333333) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 16, 31); trade_tick.Price = 21050; trade_tick.Volume = 99; trade_tick.Initiator =  -1; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -  10) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  -186) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - -2.9245283019 ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  63.6         ) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.3         ) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 16, 41); trade_tick.Price = 21050; trade_tick.Volume = 96; trade_tick.Initiator =  1 ; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -  11) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  -90 ) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - -1.3524590164 ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  66.5454545455) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.3636363636) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 16, 51); trade_tick.Price = 21050; trade_tick.Volume = 30; trade_tick.Initiator =  1 ; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -  12) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  -60 ) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - -0.9448818898 ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  63.5         ) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.4166666667) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 17, 1 ); trade_tick.Price = 21050; trade_tick.Volume = 55; trade_tick.Initiator =  1 ; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -  12) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  18  ) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - 0.2720403023  ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  66.1666666667) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.5         ) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 17, 11); trade_tick.Price = 21050; trade_tick.Volume = 8 ; trade_tick.Initiator =  1 ; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -  12) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  -63 ) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - -1.0603085554 ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  59.4166666667) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.5         ) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 17, 21); trade_tick.Price = 21050; trade_tick.Volume = 26; trade_tick.Initiator =  -1; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -  12) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  -63 ) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - -1.0603085554 ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  59.4166666667) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.5         ) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 17, 31); trade_tick.Price = 21050; trade_tick.Volume = 7 ; trade_tick.Initiator =  -1; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -  12) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  -108) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - -1.9002932551 ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  56.8333333333) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.4166666667) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 17, 41); trade_tick.Price = 21050; trade_tick.Volume = 23; trade_tick.Initiator =  1 ; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -  12) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  4   ) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - 0.0779220779  ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  51.3333333333) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.5         ) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 17, 51); trade_tick.Price = 21050; trade_tick.Volume = 38; trade_tick.Initiator =  1 ; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -  12) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  114 ) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - 2.3505154639  ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  48.5         ) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.5833333333) < 0.01); CPPUNIT_ASSERT(abs(tta.CovInitr() -  0.05808080808) < 0.01); CPPUNIT_ASSERT(abs(tta.CorrInitr() -  0.0597402597) < 0.01);
  trade_tick.hms = HMS( 9, 18, 1 ); trade_tick.Price = 21050; trade_tick.Volume = 86; trade_tick.Initiator =  -1; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -  12) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  103 ) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - 2.084317032   ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  49.4166666667) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.5833333333) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 18, 11); trade_tick.Price = 21050; trade_tick.Volume = 8 ; trade_tick.Initiator =  -1; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -  12) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  122 ) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - 2.5505226481  ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  47.8333333333) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.5833333333) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 18, 21); trade_tick.Price = 21050; trade_tick.Volume = 26; trade_tick.Initiator =  -1; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -  12) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  -2  ) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - -0.0478087649 ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  41.8333333333) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.5         ) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 18, 31); trade_tick.Price = 21050; trade_tick.Volume = 93; trade_tick.Initiator =  -1; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -  12) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  4   ) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - 0.0967741935  ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  41.3333333333) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.5         ) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 18, 41); trade_tick.Price = 21050; trade_tick.Volume = 91; trade_tick.Initiator =  1 ; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -  12) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  -1  ) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - -0.0244399185 ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  40.9166666667) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.5         ) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 18, 51); trade_tick.Price = 21050; trade_tick.Volume = 69; trade_tick.Initiator =  -1; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -  12) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  -100) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - -2.2641509434 ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  44.1666666667) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.4166666667) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 19, 1 ); trade_tick.Price = 21050; trade_tick.Volume = 22; trade_tick.Initiator =  -1; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -  12) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  -177) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - -4.2736418511 ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  41.4166666667) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.3333333333) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 19, 11); trade_tick.Price = 21050; trade_tick.Volume = 72; trade_tick.Initiator =  -1; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -  12) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  -257) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - -5.4973262032 ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  46.75        ) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.25        ) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 19, 21); trade_tick.Price = 21050; trade_tick.Volume = 88; trade_tick.Initiator =  -1; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -  12) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  -319) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - -6.1444622793 ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  51.9166666667) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.25        ) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 19, 31); trade_tick.Price = 21050; trade_tick.Volume = 22; trade_tick.Initiator =  -1; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -  12) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  -334) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - -6.2821316614 ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  53.1666666667) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.25        ) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 19, 41); trade_tick.Price = 21050; trade_tick.Volume = 74; trade_tick.Initiator =  1 ; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -  12) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  -283) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - -4.9288824383 ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  57.4166666667) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.25        ) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 19, 51); trade_tick.Price = 21050; trade_tick.Volume = 96; trade_tick.Initiator =  1 ; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -  12) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  -225) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - -3.6144578313 ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  62.25        ) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.25        ) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 20, 1 ); trade_tick.Price = 21050; trade_tick.Volume = 44; trade_tick.Initiator =  1 ; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -  12) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  -95 ) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - -1.6170212766 ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  58.75        ) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.3333333333) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 20, 11); trade_tick.Price = 21050; trade_tick.Volume = 24; trade_tick.Initiator =  -1; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -  12) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  -111) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - -1.8474341193 ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  60.0833333333) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.3333333333) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 20, 21); trade_tick.Price = 21050; trade_tick.Volume = 11; trade_tick.Initiator =  -1; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -  12) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  -96 ) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - -1.6317280453 ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  58.8333333333) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.3333333333) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 20, 31); trade_tick.Price = 21050; trade_tick.Volume = 46; trade_tick.Initiator =  1 ; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -  12) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  43  ) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - 0.7830045524  ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  54.9166666667) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.4166666667) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 20, 41); trade_tick.Price = 21050; trade_tick.Volume = 13; trade_tick.Initiator =  -1; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -  12) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  -61 ) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - -1.2598967298 ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  48.4166666667) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.3333333333) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );
  trade_tick.hms = HMS( 9, 20, 51); trade_tick.Price = 21050; trade_tick.Volume = 13; trade_tick.Initiator =  -1; tta.Add(trade_tick); CPPUNIT_ASSERT(abs(tta.NoOfTrades() -  12) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBRaw() -  -5  ) < 0.1); CPPUNIT_ASSERT(abs(tta.IMBNmlzd() - -0.1142857143 ) < 0.01); CPPUNIT_ASSERT(abs(tta.MeanVolume() -  43.75        ) < 0.1); CPPUNIT_ASSERT(abs(tta.ProbBuyerInitiated() -  0.3333333333) < 0.01); CPPUNIT_ASSERT(true                                       ); CPPUNIT_ASSERT(true                                       );



  return;
}


void TestTrdTickAna::setUp()
{
}

void TestTrdTickAna::tearDown()
{
}

CppUnit::Test *TestTrdTickAna::suite()
{
  CppUnit::TestSuite *suiteOfTests = new CppUnit::TestSuite("TestTrdTickAna");

  suiteOfTests->addTest(new CppUnit::TestCaller<TestTrdTickAna>(
        "TestTrdTickAna",
        &TestTrdTickAna::RunTest));

  return suiteOfTests;
}
