#ifndef _CONSTANTS_H_
#define _CONSTANTS_H_
//#define _ATU_LOGGER_INITIAL_SLEEP_SECOND_ 1
#define _ATU_TIMER_DEFAULT_KEY_ 12766
#define _ATU_TIMER_SLAVE_SLEEP_SECOND_ 0.01 //10
#define _ATU_TIMER_MASTER_DAEMON_PING_SECOND_ 15
#define _ATU_TIMER_CHECK_MASTER_SLAVE_DELAY_USEC_ 1000
#define _ATU_TIMER_CHECK_MASTER_SLAVE_DELAY_RETRY_ 1000
#define _ATU_SLEEP_SHORT_MOMENT_ 	1000*100
#define _ATU_SLEEP_LONG_MOMENT_  	1000*1000
//#define _ATU_ORC_ORDER_REFERENCE_FIELD_ "ATU_ORC_03-057818"
#define _ATU_SLEEP_AFTER_EACH_BACKTEST_ 1000*1000*0.5
#define _ATU_BIDASKTRADE_SPREAD_LIMIT_ 1000
#define _ATU_HOT_CONFIG_CHANGE_PERIOD_IN_MS_ 1000
#define _ATU_PARSED_MARKET_DATA_CONNECTOR_WAIT_BETWEEN_GETLINE_ 100
#define _ATU_DELAY_SHUTDOWN_SEC_ 5
#define _ATU_PARSED_MARKET_DATA_CONNECTOR_READ_TILL_END_ 1
#define _ATU_ALGOSTRATEGY_CLOSEACTION_DURATION_ 2
#define _ATU_ORDERSERVER_TIME_EVENT_LOOP_PERIOD_IN_MS_ 1000
#define _ATU_MAX_ATTEMPT_DELETE_COUNT_ 3000
#define _ATU_TIMESTAMP_LENGTH_ 8 + 1 + 6 + 1 + 6
#define _ATU_SHORT_TIMESTAMP_LENGTH_ 6
#define _ATU_MARKETDATA_DEFAULT_NULL 999999
#define _ATU_EPS 0.000001
#endif //_CONSTANTS_H_
